image: debian/unstable
packages:
  - nodejs
  - npm
  - rsync
secrets:
  - eefc72cb-a612-4b95-a3e4-dae77d4f1fcf
tasks:
  - install: |
      cd communs.numerique.gouv.fr
      npm install
      npx eleventy
  - upload: |
      cd communs.numerique.gouv.fr
      rsync -e "ssh -o StrictHostKeyChecking=no" -av --delete _site/ web@libre-01.infra.data.gouv.fr:/home/web/websites/code.gouv.fr_home/preproduction/
triggers:
  - action: email
    condition: failure
    to: bastien.guerry@code.gouv.fr
